stages:
  - build
variables:
  FAILFASTCI_NAMESPACE: 'failfast-ci'
  IMAGE: quay.io/ant31/ghrelease

.docker: &docker
  variables:
    DOCKER_HOST: tcp://localhost:2375
  image: docker:17.06-git
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io
  services:
     - docker:17.06-dind
  tags:
    - kubernetes

docker-build:
  <<: *docker
  stage: build
  script:
    - docker build -t $IMAGE:$CI_BUILD_REF_NAME .
    - docker push $IMAGE:$CI_BUILD_REF_NAME
